- hosts: all
  roles:
    - fetch-artifacts
    - role: docker-push-containers
      registry: "{{ docker_registry }}"
      when: publish_containers

- hosts: localhost
  roles:
    - role: add-fileserver
      fileserver: "{{ site_pulp }}"

- hosts: "{{ site_pulp.fqdn }}"
  roles:
    - contrail-common-libs2
    - upload-artifacts
