- name: Check if Zuul overrode the registry port
  stat:
    path: "{{ zuul.executor.work_root }}/saved_vars.yaml"
  register: varfile
  delegate_to: localhost

- name: Get the overridden registry port
  include_vars:
    file: "{{ zuul.executor.work_root }}/saved_vars.yaml"
  when: varfile.stat.isreg is defined and varfile.stat.isreg

- name: Set default registry port if not overridden
  set_fact:
    registry_port: "{{ docker_registry.port }}"
  when: registry_port is not defined

- name: Register docker package name
  set_fact:
    docker_pkgname: >-
      {%- if linux_distribution == 'centos' -%}
      docker
      {%- elif linux_distribution == 'ubuntu' -%}
      docker.io
      {%- endif -%}
  when: linux_distribution is defined

- name: Install build dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ docker_pkgname | default('docker') }}"
    - iproute
  become: True
  become_user: root

- name: Configure docker insecure registries
  copy:
    content: |
      {
        "insecure-registries": ["{{ contrail_docker_registry }}",
                                "{{ site_pulp.fqdn }}:{{ site_pulp.registry_port }}"]
      }
    dest: /etc/docker/daemon.json
  become: True
  become_user: root

- name: Ensure that docker daemon is running
  service:
    name: docker
    state: restarted
  become: True
  become_user: root

