- name: Prepare packaging variables
  contrail_packaging:
    zuul: "{{ zuul }}"
    release_type: "{{ release_type }}"

- name: Check if the artifacts source dir exists on executor
  stat:
    path: "{{ zuul.executor.work_root }}/artifacts"
  register: artifacts_dir
  become: true

- name: upload artifacts to pulp server
  synchronize:
    src: "{{ executor_package_dir }}"
    dest: /var/www/html/artifacts/{{ packaging.repo_name }}
  when: artifacts_dir.stat.isdir is defined and artifacts_dir.stat.isdir
