- name: Set paths
  set_fact:
    test_container_build_dir: "{{ ansible_env.HOME }}/src/review.opencontrail.org/Juniper/contrail-test"
    rpm_repo_config_dir: /etc/yum.repos.d

- name: Get list of repo files
  find:
    paths: "{{ rpm_repo_config_dir }}/"
  register: repo_file_list

- name: Copy the repo files to containers build context
  copy:
    src: "{{ item.path }}"
    dest: "{{ test_container_build_dir }}/docker/test/{{ item.path | basename }}"
    remote_src: true
  with_items:
    - "{{ repo_file_list.files }}"

- name: Check if Zuul overrode the registry port
  stat:
    path: "{{ zuul.executor.work_root }}/saved_vars.yaml"
  register: varfile
  delegate_to: localhost

- name: Get the overridden registry port
  include_vars:
    file: "{{ zuul.executor.work_root }}/saved_vars.yaml"
  when: varfile.stat.isreg is defined and varfile.stat.isreg

- name: Set default registry port if not overridden
  set_fact:
    registry_port: "{{ docker_registry.port }}"
  when: registry_port is not defined

- name: Build container contrail-test-base
  shell: "./build-container.sh base --registry-server {{ docker_registry.fqdn }}:{{ docker_registry.port }}"
  become: true
  args:
    chdir: "{{ test_container_build_dir }}"
  tags:
    - skip_ansible_lint # ANSIBLE0013

- name: Build container contrail-test-test (and push it)
  shell: |
    ./build-container.sh test \
    --tag {{ contrail_container_tag }}-{{ linux_distribution }}-{{ openstack_version }} \
    --registry-server {{ contrail_docker_registry }} \
    --sku {{ openstack_version }} \
    --contrail-repo {{ contrail_package_repository }} \
    --post
  become: true
  args:
    chdir: "{{ test_container_build_dir }}"
  tags:
    - skip_ansible_lint # ANSIBLE0013
