---

- hosts: builder
  roles:
    - role: fetch-packages

- hosts: localhost
  roles:
    - contrail-common-libs2
    - role: publish-rpm-nexus
      when: release_type == 'continuous-integration'
      remote_repo_path: "{{ nexus.repos.yum }}/{{ packaging.repo_names[hostvars['builder'].ansible_distribution] }}"
    - role: publish-rpm-nexus
      when: release_type == 'nightly'
      remote_repo_path: "{{ nexus.repos.yum_nightly }}/{{ packaging.repo_names[hostvars['builder'].ansible_distribution] }}"
