---

- hosts: builder
  roles:
    - role: fetch-packages

- hosts: localhost
  roles:
    - contrail-common-libs2
    - role: publish-rpm-artifactory
      when: release_type == 'continuous-integration'
      remote_repo_path: "http://svl-artifactory.juniper.net/artifactory/yum-contrail-ci-build/{{ packaging.repo_names[hostvars['builder'].ansible_distribution] }}"
    - role: publish-rpm-artifactory
      when: release_type == 'nightly'
      remote_repo_path: "http://svl-artifactory.juniper.net/artifactory/contrail-ci-yum-nightly/{{ packaging.repo_names[hostvars['builder'].ansible_distribution] }}"
  post_tasks:
    # FIXME: https://contrail-jws.atlassian.net/browse/JD-478
    - name: return repository location back to zuul for children jobs
      zuul_return:
        data:
          contrail_container_tag: '{{ packaging.docker_version }}'
      delegate_to: localhost
