- name: Start all containers that were stopped during kolla docker daemon restart (pass one - network containers)
  shell: 'docker ps -a  --format "{% raw %}{{.Names}}{% endraw %}" | while read line; do docker start $line; done'
  ignore_errors: true
  become: true

- name: Start all containers that were stopped during kolla docker daemon restart (pass two - all containers)
  shell: 'docker ps -a  --format "{% raw %}{{.Names}}{% endraw %}" | while read line; do docker start $line; done'
  ignore_errors: true
  become: true

- name: Wait for services startup
  wait_for:
    timeout: 120

- name: Set variables
  set_fact:
    testrunner_image: "{{ docker_registry.fqdn }}:{{ registry_port }}/contrail-test-test:{{ contrail_version }}"
    repos_dir: "{{ ansible_env.HOME }}/src/{{ zuul.project.canonical_hostname }}/Juniper"
    control_ip: "{{ ansible_default_ipv4.address }}"

- name: Reload facts after DHCP address setup
  setup:
    gather_timeout: 300

- name: Copy hosts template
  template:
    src: contrail_test_input.j2
    dest: "{{ ansible_env.HOME }}/contrail_test_input.yaml"

- name: Pull the testrunner image
  docker_image:
    name: "{{ testrunner_image }}"
  become: yes

- name: Run the sanity test
  command: |
    "{{ repos_dir }}/contrail-test-ci/testrunner.sh run \
        -P {{ ansible_env.HOME }}/contrail_test_input.yaml \
        -k /root/.ssh/id_rsa \
        -f {{ test_target }} '{{ testrunner_image }}'"
  become: yes
  ignore_errors: yes

- name: test the xml report for failures
  shell: "[ x\"$(grep testsuite /root/contrail-test-runs/*/reports/TESTS-TestSuites.xml  | grep -o  'failures=\\S\\+' | uniq)\" = x'failures=\"0\"' ]"
  become: yes
