- name: Get container list
  shell: |
    # this magical part returns list of containers from the current buildset
    # e.g. all containers matching 'master-5' in their tag
    for repo in $(curl -s {{ docker_registry.fqdn }}:{{ docker_registry.port }}/v2/_catalog | jq -r '.[] | join(" ")'); do
      for tag in $(curl -s {{ docker_registry.fqdn }}:{{ docker_registry.port }}/v2/$repo/tags/list | jq -r '.tags | sort | .[] | select( . | contains("{{ contrail_container_tag }}"))'); do
        echo $repo:$tag
      done
    done
  register: container_list

# XXX: perhaps we should manage "centos7-ocata" part via secrets
- name: Register variable for latest release
  set_fact:
    container_latest_release: "ocata-{{ contrail_container_tag }}"

- name: Pull containers
  command: "docker pull {{ docker_registry.fqdn }}:{{ docker_registry.port }}/{{ item }}"
  with_items: "{{ container_list.stdout_lines }}"
  become: true
  # Due to some mysterious causes, it seems to fail occassionally, so need to retry it
  register: result
  retries: 3
  delay: 10
  until: result.rc == 0


- name: Retag containers for master branch
  block:
    # ci-repo/container -> dockerhub/container
    - name: Retag containers - add dockerhub namespace
      command: "docker tag {{ docker_registry.fqdn }}:{{ docker_registry.port }}/{{ item }} {{ dockerhub.namespace }}/{{ item }}"
      with_items: "{{ container_list.stdout_lines }}"

    # ci-repo/ocata-master-5 -> ci-repo/latest
    - name: Retag containers - ci-repo/latest
      command: "docker tag {{ docker_registry.fqdn }}:{{ docker_registry.port }}/{{ item }} {{ docker_registry.fqdn }}:{{ docker_registry.port }}/{{ item | regex_replace(':.*$',':latest') }}"
      when: item | search(container_latest_release)
      with_items: "{{ container_list.stdout_lines }}"

    # ci-repo/ocata-master-5 -> dockerhub/latest
    - name: Retag containers - dockerhub/latest
      command: "docker tag {{ docker_registry.fqdn }}:{{ docker_registry.port }}/{{ item }} {{ dockerhub.namespace }}/{{ item | regex_replace(':.*$', ':latest') }}"
      when: item | search(container_latest_release)
      with_items: "{{ container_list.stdout_lines }}"

    # ci-repo/ocata-master-5 -> opencontrailnightly/master-5
    - name: Retag containers - dockerhub/no-openstack-tag
      command: "docker tag {{ docker_registry.fqdn }}:{{ docker_registry.port }}/{{ item }} {{ dockerhub.namespace }}/{{ item | regex_replace('([^:]+):([^-]+)-([^-]+)-(.+)$', '\\g<1>:\\g<3>-\\g<4>') }}"
      when: item | search(container_latest_release)
      with_items: "{{ container_list.stdout_lines }}"

  become: true
  when: zuul.branch == 'master'

- name: Retag containers - ci-repo/no-openstack-tag
  # ci-repo/ocata-master-5 -> opencontrailnightly/master-5
  command: "docker tag {{ docker_registry.fqdn }}:{{ docker_registry.port }}/{{ item }} {{ docker_registry.fqdn }}:{{ docker_registry.port }}/{{ item | regex_replace('([^:]+):([^-]+)-([^-]+)-(.+)$', '\\g<1>:\\g<3>-\\g<4>') }}"
  when: item | search(container_latest_release)
  with_items: "{{ container_list.stdout_lines }}"
  become: true

- name: Log in to dockerhub
  command: "docker login -u {{ dockerhub.username }} -p {{ dockerhub.password }}"
  no_log: true
  become: true

- name: Get local container list
  shell: |
    for i in `docker images | grep contrail | awk '{printf "%s:%s\n", $1,$2;}'`; do
      echo $i;
    done
  register: local_container_list
  become: true

- name: Push all containers
  command: "docker push {{ item }}"
  with_items: "{{ local_container_list.stdout_lines }}"
  become: true
  # upload fails a lot :(
  register: result
  retries: 3
  delay: 15
  until: result.rc == 0

- name: Cleanup all docker images
  command: "docker rmi -f {{ item }}"
  with_items: "{{ local_container_list.stdout_lines }}"
  become: true

- name: Log out of Dockerhub
  command: "docker logout"
  become: true
