- name: set variables
  set_fact:
    publisher_path: "{{ ansible_env.HOME }}/src/github.com/Juniper/contrail-publisher"

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release
    - python34
    - python34-pip

- name: install virtualenv for publisher
  command: python3 -m venv venv
  args:
    chdir: "{{ publisher_path }}"

- name: install requirements
  shell: |
    . venv/bin/activate
    pip3 install -r requirements.txt
  args:
    chdir: "{{ publisher_path }}"

- name: copy publisher config
  copy:
    src: publisher-config.yaml
    dest: "{{ publisher_path }}/publisher-config.yaml"


- name: Push to internal registry
  shell: |
    . venv/bin/activate
    python3 publisher.py --config publisher-internal-config.yaml --build-registry 10.84.5.81:{{ docker_registry_port }} --release {{ contrail_packaging.version.public }} --build {{ build_number }} --openstack_release {{ item }}
  args:
    chdir: "{{ publisher_path }}"
  with_items:
    - ocata
    - newton

- name:
  when: "{{ contrail_packaging.version.public }} == 'master'}}"
  block:
    - name: Log in to dockerhub
      command: "docker login -u {{ dockerhub.username }} -p {{ dockerhub.password }}"
      no_log: true
      become: true
    
    - name: Push to Dockerhub
      shell: |
        . venv/bin/activate
        python3 publisher.py --config publisher-dockerhub-config.yaml --build-registry 10.84.5.81:{{ docker_registry_port }} --release {{ contrail_packaging.version.public }} --build {{ build_number }} --openstack_release {{ item }}
      args:
        chdir: "{{ publisher_path }}"
      with_items:
        - ocata
        - newton
    
    - name: Log out of Dockerhub
      command: "docker logout"
      become: true
