- name: Get container list
  shell: |
    for repo in $(curl -s {{ docker_registry.fqdn }}:{{ docker_registry.port }}/v2/_catalog | jq -r '.[] | join(" ")' | sed -e 's/\S*kolla\S*//g'); do
      for tag in $(curl -s {{ docker_registry.fqdn }}:{{ docker_registry.port }}/v2/$repo/tags/list | jq -r '.tags | sort | .[-1]'); do
        echo $repo:$tag
      done
    done
  register: container_list

- name: Pull containers
  shell: "docker pull {{ docker_registry.fqdn }}:{{ docker_registry.port }}/{{ item }}"
  retries: 3
  delay: 5
  register: result
  until: result.rc == 0
  with_items: "{{ container_list.stdout_lines }}"
  become: true

- name: Log in to dockerhub
  shell: "docker login -u {{ dockerhub.username }} -p {{ dockerhub.password }}"
  no_log: true
  become: true

- name: Retag containers
  shell: "docker tag {{ docker_registry.fqdn }}:{{ docker_registry.port }}/{{ item }} {{ dockerhub.namespace }}/{{ item }}"
  with_items: "{{ container_list.stdout_lines }}"
  become: true

- name: Tag containers as latest
  shell: "docker tag {{ dockerhub.namespace }}/{{ item }} {{ dockerhub.namespace }}/{{ item | regex_replace(':.*$',':latest') }}"
  with_items: "{{ container_list.stdout_lines }}"
  become: true

- name: Push containers
  shell: |
    docker push {{ dockerhub.namespace }}/{{ item }}
  retries: 3
  delay: 5
  register: result
  until: result.rc == 0
  with_items: "{{ container_list.stdout_lines }}"
  become: true

- name: Push tag latest
  shell: |
    docker push {{ dockerhub.namespace }}/{{ item | regex_replace(':.*$',':latest') }}
  retries: 3
  delay: 5
  register: result
  until: result.rc == 0
  with_items: "{{ container_list.stdout_lines }}"
  become: true

- name: Remove containers
  shell: |
    docker rmi {{ docker_registry.fqdn }}:{{ docker_registry.port }}/{{ item }}
    docker rmi {{ dockerhub.namespace }}/{{ item }}
    docker rmi {{ dockerhub.namespace }}/{{ item | regex_replace(':.*$',':latest') }}
  with_items: "{{ container_list.stdout_lines }}"
  become: true
