- name: Get container list
  shell: |
    for repo in $(curl -s {{ docker_registry.fqdn }}:{{ docker_registry.port }}/v2/_catalog | jq -r '.[] | join(" ")' | sed -e 's/\S*kolla\S*//g'); do
      for tag in $(curl -s {{ docker_registry.fqdn }}:{{ docker_registry.port }}/v2/$repo/tags/list | jq -r '.tags | sort | .[-1]'); do
        echo $repo:$tag
      done
    done
  register: container_list

- name: Pull containers
  shell: "docker pull {{ docker_registry.fqdn }}:{{ docker_registry.port }}/{{ item }}"
  with_items: "{{ container_list.stdout_lines }}"
  become: true

- name: Log in to dockerhub
  shell: "docker login -u {{ dockerhub.username }} -p {{ dockerhub.password }}"
  no_log: true
  become: true

- name: Retag containers - add dockerhub namespace
  shell: "docker tag {{ docker_registry.fqdn }}:{{ docker_registry.port }}/{{ item }} {{ dockerhub.namespace }}/{{ item }}"
  with_items: "{{ container_list.stdout_lines }}"
  become: true

- name: Retag ocata containers - add master-date tag
  shell: "docker tag {{ dockerhub.namespace }}/{{ item }} {{ dockerhub.namespace }}/{{ item | regex_replace('5.0', 'master') | regex_replace('master-(.[^-]*)-.*', 'master-\\1') }}"
  when: item | search('ocata')
  with_items: "{{ container_list.stdout_lines }}"
  become: true

- name: Retag containers - add latest tag
  shell: "docker tag {{ dockerhub.namespace }}/{{ item }} {{ dockerhub.namespace }}/{{ item | regex_replace(':.*$',':latest') }}"
  when: item | search('ocata')
  with_items: "{{ container_list.stdout_lines }}"
  become: true

- name: Push all containers
  shell: "docker push $(docker images -q | grep {{ dockerhub.namespace }})"
  become: true

- name: Cleanup all docker images
  shell: docker rmi -f $(docker images | grep contrail)
  become: true
