- name: Log in to dockerhub
  command: "docker login -u {{ dockerhub.username }} -p {{ dockerhub.password }}"
  no_log: true
  become: true

- name: Run publishing script
  command: publisher.py

- name: Log out of Dockerhub
  command: "docker logout"
  become: true
