#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi

cat /etc/resolv.conf.ORIG
echo ";" > /etc/resolv.conf.ORIG
echo "; Emptied from inside nb01:/etc/nodepool/elements/contrail-builder/finalise.d/10-resolvconf" >> /etc/resolv.conf.ORIG

