#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [[ $DISTRO_NAME == "centos7" ]]; then
mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo_bak
fi

yum update -y
yum clean all

#if [[ $DISTRO_NAME == "centos7" ]]; then
#mv /etc/yum.repos.d/CentOS-Base.repo_bak /etc/yum.repos.d/CentOS-Base.repo
#fi
