- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yaml"
    - "{{ ansible_os_family | lower }}.yaml"
    - "default.yaml"

- name: Include OpenStack-specific repos
  include_vars: "{{ ansible_distribution | lower }}_openstack_{{ openstack_version }}.yaml"
  when: 'ansible_distribution == "RedHat"'

- name: Add OpenStack repos to repos_add
  set_fact:
    repos_add: "{{ repos_add }} + {{ openstack_repos_add }}"
  when: 'ansible_distribution == "RedHat"'

- name: Disable subscription-manager on RHEL
  command: subscription-manager config --rhsm.manage_repos=0
  become: yes
  become_user: root
  when: 'ansible_distribution == "RedHat"'

- name: Remove the upstream yum repos
  yum_repository:
    name: "{{ item.name }}"
    file: "{{ item.file }}"
    state: absent
  with_items: "{{ repos_remove }}"
  become: yes
  become_user: root

- name: Prepare local base yum mirror repo file
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    file: "{{ repos_file }}"
    baseurl: "{{ repos_baseurl }}/{{ item.repo }}/"
    enabled: yes
    gpgcheck: no
  with_items: "{{ repos_add }}"
  become: yes
  become_user: root

- name: Prepare epel mirror repo file
  yum_repository:
    name: epel-mirror
    description: CentOS epel mirror
    file: epel
    baseurl: "http://{{ docker_registry.fqdn }}/pulp/repos/centos74-epel/"
    enabled: "{{ use_epel }}"
    gpgcheck: no
  become: yes
  become_user: root

- name: Prepare third party cache yum repo file
  yum_repository:
    name: contrail-tpc
    description: Contrail third-party dependencies
    file: contrail-tpc
    baseurl: "http://{{ docker_registry.fqdn }}/pulp/repos/opencontrail-tpc-{{ tpc_branch }}/"
    enabled: yes
    gpgcheck: no
  become: yes
  become_user: root
