- hosts: localhost
  roles:
    - role: add-fileserver
      fileserver: "{{ site_logs }}"
    - emit-ara-html

- hosts: "{{ site_logs.fqdn }}"
  roles:
    - role: upload-logs
      zuul_log_url: "http://logs.openstack.org"
