---

# Contrail Publisher configuration
#
# This configuration describes a process of copying artifacts
# from public per-review registry into the public ci-repo one.
#
# The build registry url can be overridden from the command
# line by passing `--build-override 10.84.5.81:port`

registries:
  - name: build
    url: 10.84.5.81:32000
    source: True
    untrusted: True
  - name: dockerhub
    url: opencontrailnightly
    untrusted: False

# the default distribution for images
distribution: centos

# Image overrides:
#
# Overrides can be used to change the behavior on the per-image basis. This
# can be used to implement custom tagging for RHEL, select which registries
# to push images to etc.
#
# Currently supported keys are:
#
#   - `image_matcher`
#   - `tag_matcher`
#   - `registries`
#   - `release_tags`
#   - `source_tag`
#   - `distribution`
#
image_overrides:
  # contrail-go is pushed with {{ release }}-{{ build_no }}
  - image_matcher: "^contrail-go$"
    source_tag: "5.1.0-0.{{ build_no }}"
    release_tags:
      - "5.1.0-0.{{ build_no }}"
      - "latest"
    registries:
      - dockerhub

  - image_matcher: developer-sandbox
    source_tag: "5.1.0-0.{{ build_no }}"
    release_tags:
      - "5.1.0-0.{{ build_no }}"
      - "5.1.0-latest"
      - "5.1.0"
      - "latest"
      # keep old tags for now
      - "master-{{ build_no }}"
      - "master"
    registries:
      - dockerhub

  - image_matcher: developer-sandbox
    source_tag: "{{ release }}-0.{{ build_no }}"
    release_tags:
      - "{{ release }}-0.{{ build_no }}"
      - "{{ release }}-latest"
      - "{{ release }}"
      # keep old tags for now
      - "{{ release }}"
      - "{{ release }}-{{ build_no }}"
    registries:
      - dockerhub

  - image_matcher: "^.*$"
    tag_matcher: "^5\\.1\\.0-0\\.d+-newton$"
    release_tags:
      - "5.1.0-0.{{ build_no }}-newton"
      - "5.1.0-latest-newton"
      # keep old tags for now
      - "newton-master-{{ build_no }}"
      - "newton-master-latest"
    registries:
      - dockerhub

  - image_matcher: "^.*$"
    tag_matcher: "^5\\.1\\.0-0\\.d+-ocata$"
    release_tags:
      - "5.1.0-0.{{ build_no }}-ocata"
      - "5.1.0-latest-ocata"
      # keep old tags for now
      - "ocata-master-{{ build_no }}"
      - "ocata-master-latest"
    registries:
      - dockerhub

  - image_matcher: "^.*$"
    tag_matcher: "^5\\.1\\.0-0\\.d+-queens$"
    release_tags:
      - "5.1.0-0.{{ build_no }}-queens"
      - "5.1.0-0.{{ build_no }}"
      - "5.1.0-latest-queens"
      - "5.1.0-latest"
      - "latest"
      # keep old tags for now
      - "queens-master-{{ build_no }}"
      - "queens-master-latest"
      - "master-{{ build_no }}"
      - "master-latest"
    registries:
      - dockerhub

  - image_matcher: "^.*$"
    tag_matcher: "^5\\.1\\.0-0\\.d+-rocky$"
    release_tags:
      - "5.1.0-0.{{ build_no }}-rocky"
      - "5.1.0-latest-rocky"
      # keep old tags for now
      - "rocky-master-{{ build_no }}"
      - "rocky-master-latest"
    registries:
      - dockerhub

# rhel_marker and openstack_release have two variants: _lhs and _rhs depending
# on how they are used:
#
# They either end (lhs) or start (rhs) with a hyphen, to make combining them with other
# parts of the source tag easier.

# WARNING: source tags have wrong release - the micro part is missing.
# ocata-5.0-27 and newton-5.0-27
source_tag: "{{ openstack_release_lhs }}{{ release }}-{{ build_no }}"

# The default set of tags to apply to images.
# XXX(kklimonda): that seems pointless, we override everything.
release_tags:
  # 5.0.0-0.27-newton (-ocata is being overridden above)
  - "{{ release }}-0.{{ build_no }}{{ openstack_release_rhs }}"

