---

- name: Add review.opencontrail.org remote
  command: git remote add gerrit "https://{{ item }}"
  args:
    chdir: "{{ ansible_env.HOME }}/src/{{ item }}"
  failed_when: false
  with_items:
    - review.opencontrail.org/Juniper/contrail-controller
    - review.opencontrail.org/tungstenfabric/tf-build
    - review.opencontrail.org/tungstenfabric/tf-vrouter
    - review.opencontrail.org/Juniper/contrail-sandesh
    - review.opencontrail.org/Juniper/contrail-generateDS
    - review.opencontrail.org/tungstenfabric/tf-common
    - review.opencontrail.org/tungstenfabric/tf-analytics
    - review.opencontrail.org/tungstenfabric/tf-api-client
    - review.opencontrail.org/tungstenfabric/tf-vcenter-manager
    - review.opencontrail.org/tungstenfabric/tf-vcenter-fabric-manager
  tags:
    # Ignore ANSIBLE0006: Can not use git module for adding remotes
    - skip_ansible_lint

- name: Fetch all remotes
  command: git fetch --all
  args:
    chdir: "{{ ansible_env.HOME }}/src/{{ item }}"
  with_items:
    - review.opencontrail.org/Juniper/contrail-controller
    - review.opencontrail.org/tungstenfabric/tf-build
    - review.opencontrail.org/tungstenfabric/tf-vrouter
    - review.opencontrail.org/Juniper/contrail-sandesh
    - review.opencontrail.org/Juniper/contrail-generateDS
    - review.opencontrail.org/tungstenfabric/tf-common
    - review.opencontrail.org/tungstenfabric/tf-analytics
    - review.opencontrail.org/tungstenfabric/tf-api-client
    - review.opencontrail.org/tungstenfabric/tf-vcenter-manager
    - review.opencontrail.org/tungstenfabric/tf-vcenter-fabric-manager
  tags:
    # Ignore ANSIBLE0006: Can not use git module for fetching
    - skip_ansible_lint
  retries: 5
  delay: 3
  register: fetch_result
  until: fetch_result.rc == 0
