---

- name: Ensure that hostname is in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}"
  become: true
  become_user: root

# Some tests (like test.test_flow.FlowQuerierTest.test_1_noarg_query) expect
# PST timezone, and fail otherwise.
- name: Change the timezone to America/Los_Angeles
  timezone:
    name: America/Los_Angeles
  become: true
  become_user: root

- name: Copy over unittest scripts to the builder VM
  copy:
    src: "{{ item }}"
    dest: "."
    mode: 0755
  with_fileglob:
    - "*"

- name: Update yum packages
  command: '{{ item }}'
  become: true
  become_user: root
  with_items:
    - yum update -y

- name: Install additional packages used by unittest scripts
  yum:
    name: "{{ item }}"
    state: present
  become: true
  become_user: root
  with_items:
    - createrepo
    - docker
    - docker-python
    - gcc
    - gdb
    - git
    - make
    - python-devel
    - python-pip
    - python36-devel
    - python36-pip
    - rpm-build
    - ruby
    - vim
    - wget
    - yum-utils
    - bash-completion
    - bash-completion-extras
    - ShellCheck
    - man-pages
    - man-db

- name: install deps
  command: make -f tools/packages/Makefile dep
  args:
    chdir: "{{ packaging.target_dir }}"
  become: true
  become_user: root

- name: fetch packages
  command: ./third_party/fetch_packages.py
  args:
    chdir: "{{ packaging.target_dir }}"
  become: true
  become_user: root

# Last version of pip that is pip-installable on Ubuntu
# without breaking system pip installation
- name: Upgrade pip
  command: pip install --ignore-installed pip==9.0.3
  become: true

- name: install python2 pypi packages
  command: "pip install {{ item }}"
  become: true
  become_user: root
  with_items:
    - future
    - tox
    - geventhttpclient

- name: install python3
  package:
    name: python3
    state: installed
  become: true

- name: install/upgrade utilities
  become: true
  command: "python3 -m pip install --upgrade {{ item }}"
  with_items:
    - virtualenv
    - scons
    - pydot
    - future
    - caniusepython3
    - future
    - tox
    - geventhttpclient

# Version of tox that does not upgrade setuptools to the newest version,
# breaking Contrail Python package build
- name: Upgrade tox
  command: pip install --ignore-installed tox==3.1.3 virtualenv<16.2.0
  become: true

- name: Run a full Contrail VNC build
  command: "scons -j {{ ansible_processor_vcpus }}"
  args:
    chdir: "{{ packaging.target_dir }}"
  become: true
  become_user: root
  environment:
    BUILD_ONLY: 1
    ZUUL_CHANGES: "{{ zuul.ref }}"
    CONTRAIL_COMPILE_WITHOUT_SYMBOLS: yes
    LC_ALL: "C"

- name: Run unittest script
  command: "{{ ansible_env.HOME }}/contrail-unittests-job.sh"
  become: true
  become_user: root
  environment:
    WORKSPACE: "{{ ansible_env.HOME }}"
    UPSTREAM_VERSION: "{{ packaging.version.upstream }}"
    ZUUL_CHANGES: "{{ zuul.ref }}"
    ZUUL_PROJECT: "{{ zuul.project.short_name }}"
    SCONS_JOBS: "1"
    LC_ALL: "C"
    VIRTUALENV_NO_DOWNLOAD: "1"
    GIT_REFS: >-
      {% set git_refs = [] -%}
      {% for item in zuul['items'] -%}
        {% set ref = "refs/changes/" + item.change[-2:] + "/" + item.change + "/" + item.patchset -%}
        {% set git_ref = item.project.short_name + "^" + ref -%}
        {% set _ =  git_refs.append(git_ref) -%}
      {% endfor -%}
      {{- git_refs|join(",") -}}

