---
- hosts: all
  roles:
    - role: fetch-docs
      srce_path: "{{ ansible_env.HOME }}/build/html"
      dstn_path: "{{ zuul.executor.work_root }}/build/html"

- hosts: all
  roles:
    - role: add-fileserver
      fileserver: "{{ site_logs }}"

- hosts: "{{ site_logs.fqdn }}"
  gather_facts: False
  roles:
    - role: upload-docs
      zuul_doc_url: "http://logs.tungsten.io"
      zuul_docserver_root: "var/www/static/infra-doc/"
      root_files: "{{ zuul.executor.work_root }}/build/html"
