---
- hosts: builder
  roles:
    - fetch-packages

- hosts: localhost
  roles:
    - role: publish-rpm-nexus
      vars:
        contrail_built_rpms_src: "{{ zuul.projects | selectattr('short_name', 'equalto', 'contrail-third-party-packages') | map(attribute='src_dir') | list | first }}/../RPMS"
